UPDATE Units SET BaseMoves = 5, BaseSightRange = 5 WHERE UnitType = 'UNIT_SETTLER';

INSERT INTO Types (Type, Kind) VALUES
	('MODIFIER_SETTLER_IGNORE_TERRAIN_COST', 'KIND_MODIFIER');
INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES
	('MODIFIER_SETTLER_IGNORE_TERRAIN_COST', 'COLLECTION_PLAYER_UNITS', 'EFFECT_ADJUST_UNIT_IGNORE_TERRAIN_COST');
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
	('TRAIT_LEADER_MAJOR_CIV', 'SETTLER_IGNORE_TERRAIN'),
	('TRAIT_LEADER_MAJOR_CIV', 'SETTLER_IGNORE_RIVERS'),
	('TRAIT_LEADER_MAJOR_CIV', 'SETTLER_IGNORE_EMBARK');
INSERT INTO Modifiers (ModifierId, ModifierType, Permanent, SubjectRequirementSetId) VALUES
	('SETTLER_IGNORE_TERRAIN', 'MODIFIER_SETTLER_IGNORE_TERRAIN_COST', 1, 'SETTLER_SPEED_REQSET'),
	('SETTLER_IGNORE_RIVERS', 'MODIFIER_PLAYER_UNITS_ADJUST_IGNORE_RIVERS', 1, 'SETTLER_SPEED_REQSET'),
	('SETTLER_IGNORE_EMBARK', 'MODIFIER_PLAYER_UNITS_ADJUST_IGNORE_SHORES', 1, 'SETTLER_SPEED_REQSET');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('SETTLER_IGNORE_TERRAIN', 'Ignore', 1),
	('SETTLER_IGNORE_TERRAIN', 'Type', 'ALL'),
	('SETTLER_IGNORE_RIVERS', 'Ignore', 1),
	('SETTLER_IGNORE_EMBARK', 'Ignore', 1);
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
	('SETTLER_SPEED_REQSET', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
	('SETTLER_SPEED_REQSET', 'REQUIRES_UNIT_IS_SETTLER');
INSERT INTO Requirements (RequirementId, RequirementType, Inverse) VALUES
	('REQUIRES_UNIT_IS_SETTLER', 'REQUIREMENT_UNIT_TYPE_MATCHES', 0);
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES
	('REQUIRES_UNIT_IS_SETTLER', 'UnitType', 'UNIT_SETTLER');